// Generated by CoffeeScript 1.7.1
(function() {
  var AgentsData, AgentsManager, AgentsRegistry, CertificateManager, StormAgent, StormData, StormRegistry, auth, jsonschema, query, util, uuid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jsonschema = require("json-schema");

  uuid = require("node-uuid");

  CertificateManager = require("http/certs").CertificateManager;

  query = require("dirty-query").query;

  auth = require("http/auth").authorization;

  util = require("util");

  StormAgent = require("stormagent");

  StormData = StormAgent.StormData;

  StormRegistry = StormAgent.StormRegistry;

  AgentsData = (function(_super) {
    var agentSchema;

    __extends(AgentsData, _super);

    agentSchema = {
      name: "Agent",
      type: "object",
      additionalProperties: true,
      properties: {
        id: {
          "type": "string",
          "required": false
        },
        stoken: {
          "type": "string",
          "required": true
        },
        serialkey: {
          "type": "string",
          "required": true
        },
        lastActivation: {
          "type": "string",
          "required": false
        },
        bolt: {
          type: "object",
          required: true,
          additionalProperties: true,
          properties: {
            uplinks: {
              type: "array",
              items: {
                type: "string",
                required: false
              }
            },
            uplinkStrategy: {
              type: "string",
              required: false
            },
            allowRelay: {
              type: "boolean",
              required: false
            },
            relayPort: {
              type: "number",
              required: false
            },
            allowedPorts: {
              type: "array",
              items: {
                type: "number",
                required: false
              }
            },
            listenPort: {
              type: "number",
              required: false
            },
            beaconInterval: {
              type: "number",
              required: false
            },
            beaconRetry: {
              type: "number",
              required: false
            },
            beaconValidity: {
              type: "number",
              required: false
            },
            ca: {
              type: "object",
              required: false,
              properties: {
                encoding: {
                  "type": "string",
                  "required": true
                },
                data: {
                  "type": "string",
                  "required": true
                }
              }
            }
          }
        }
      }
    };

    function AgentsData(id, data) {
      AgentsData.__super__.constructor.call(this, id, data, agentSchema);
    }

    return AgentsData;

  })(StormData);

  AgentsRegistry = (function(_super) {
    __extends(AgentsRegistry, _super);

    function AgentsRegistry(filename) {
      this.on("load", function(key, val) {
        var entry;
        entry = new AgentsData(key, val);
        if (entry != null) {
          entry.saved = true;
          entry.id = key;
          console.log("loading key " + key + " and val " + val);
          return this.add(key, entry);
        }
      });
      this.on('removed', function(entry) {
        if (entry.destroy != null) {
          return entry.destroy();
        }
      });
      AgentsRegistry.__super__.constructor.call(this, filename);
    }

    AgentsRegistry.prototype.get = function(key) {
      var entry;
      return entry = AgentsRegistry.__super__.get.call(this, key);
    };

    return AgentsRegistry;

  })(StormRegistry);

  AgentsManager = (function() {
    function AgentsManager(db, certMangr) {
      this.db = db;
      this.stormsigner = global.config.stormsigner;
      this.CM = certMangr;
    }

    AgentsManager.prototype.validate = function(paramId, bodyId, body) {
      var entry, err;
      if (paramId !== bodyId) {
        throw new Error("id does not match with url");
      }
      try {
        return entry = new AgentsData(bodyId, body);
      } catch (_error) {
        err = _error;
        throw new Error("invalid json data");
      }
    };

    AgentsManager.prototype.update = function(id, agent) {
      var entry, err, _agent, _ref, _ref1;
      _agent = this.db.get(id);
      if (_agent == null) {
        return null;
      } else {
        if (((_ref = agent.data) != null ? (_ref1 = _ref.bolt) != null ? _ref1.ca : void 0 : void 0) != null) {
          delete agent.data.bolt.ca;
        }
      }
      try {
        entry = new AgentsData(_agent.id, agent);
        return this.db.update(_agent.id, entry);
      } catch (_error) {
        err = _error;
        throw new Error("invalid json data");
      }
    };

    AgentsManager.prototype.create = function(agent) {
      var entry, err;
      if (agent.id == null) {
        agent.id = uuid.v4();
      }
      try {
        entry = new AgentsData(agent.id, agent);
        this.db.add(agent.id, entry);
        return entry;
      } catch (_error) {
        err = _error;
        throw new Error("invalid json data");
      }
    };

    AgentsManager.prototype.getAgent = function(id) {
      return this.db.get(id);
    };

    AgentsManager.prototype.getAgentBySerial = function(serialKey) {
      var agents;
      agents = query(this.db.db, {
        "serialkey": serialKey
      });
      if (agents != null) {
        return agents[0];
      }
    };

    AgentsManager.prototype.deleteAgent = function(id) {
      return this.db.remove(id);
    };

    AgentsManager.prototype.loadCaBundle = function(agent) {
      agent.bolt.ca = {
        encoding: "base64",
        data: new Buffer(this.CM.signerBundle(this.stormsigner)).toString("base64")
      };
      return agent;
    };

    return AgentsManager;

  })();

  this.include = function() {
    var AM;
    AM = this.settings.agent.AM;
    this.post({
      "/agents": function() {
        var agent, error;
        try {
          agent = AM.create(this.body);
          return this.send(AM.loadCaBundle(agent.data));
        } catch (_error) {
          error = _error;
          console.log("Error:" + error);
          return this.response.send(400, error);
        }
      }
    });
    this.put({
      "/agents/:id": function() {
        var entry, error, _ref;
        try {
          entry = AM.getAgent(this.params.id);
          if (entry != null) {
            AM.validate(this.params.id, this.body.id, this.body);
            if ((_ref = this.body.bolt) != null ? _ref.ca : void 0) {
              delete this.body.bolt.ca;
            }
            return this.send(AM.update(this.body.id, this.body));
          } else {
            return this.send(404);
          }
        } catch (_error) {
          error = _error;
          this.response.status(400);
          return this.response.send({
            error: "" + error
          });
        }
      }
    });
    this.put({
      "/agents/:id/status/:status": function() {
        var agent;
        agent = this.db.get(this.params.id);
        if (agent != null) {
          agent.status = this.params.status;
          AM.update(this.params.id, agent);
        } else {
          this.send(404);
        }
        return this.send(204);
      }
    });
    this.get({
      "/agents/:id": function() {
        var agent;
        agent = AM.getAgent(this.params.id);
        console.log("Ravi - get agent found ", agent);
        if (agent != null) {
          return this.send(AM.loadCaBundle(agent.data));
        } else {
          return this.send(404);
        }
      }
    });
    this.get({
      "/agents/:id/bolt": function() {
        var agent;
        agent = AM.getAgent(this.params.id);
        if (agent != null) {
          return this.send(AM.loadCaBundle(agent.data).bolt);
        } else {
          return this.send(404);
        }
      }
    });
    this.get("/agents/serialkey/:key", auth, function() {
      var agent;
      agent = AM.getAgentBySerial(this.params.key);
      if (agent != null) {
        return this.send({
          "id": agent.id,
          "serialkey": this.params.key
        });
      } else {
        return this.send(404);
      }
    });
    this.post("/agents/:id/csr", auth, function() {
      var csrRequest;
      util.log("CSR for agent " + this.params.id);
      if ((AM.getAgent(this.params.id)) != null) {
        csrRequest = {
          csr: this.body.file,
          signee: {
            "daysValidFor": global.config.signerChain.days
          },
          signer: AM.CM.get(AM.stormsigner)
        };
        return AM.CM.signCSR(csrRequest, (function(_this) {
          return function(err, cert) {
            if (err != null) {
              return _this.response.send(400);
            }
            return _this.response.send({
              "encoding": "base64",
              "data": new Buffer(cert.cert).toString("base64")
            });
          };
        })(this));
      } else {
        return this.send(404);
      }
    });
    return this.del("/agents/:id", function() {
      if ((AM.getAgent(this.params.id)) != null) {
        AM.deleteAgent(this.params.id);
        this.send(204);
        return;
      }
      return this.send(404);
    });
  };

  exports.AgentsManager = AgentsManager;

  exports.AgentsRegistry = AgentsRegistry;

}).call(this);
