// Generated by CoffeeScript 1.7.1
(function() {
  var StormTracker, auth, config, tracker;

  config = require('../package').config;

  GLOBAL.config = config;

  auth = require("http/auth");

  require("passport").use(require("http/auth").BasicStrategy);

  StormTracker = require("./stormtracker");

  tracker = new StormTracker;

  tracker.run();

}).call(this);
