// Generated by CoffeeScript 1.7.1
(function() {
  var AgentsManager, AgentsRegistry, CertificateRegistry, StormAgent, StormTracker,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  StormAgent = require("stormagent");

  AgentsRegistry = require("http/agents").AgentsRegistry;

  AgentsManager = require("http/agents").AgentsManager;

  CertificateRegistry = require("security/certificate").CertificateRegistry;

  StormTracker = (function(_super) {
    __extends(StormTracker, _super);

    function StormTracker() {
      var CertificateFactory;
      StormTracker.__super__.constructor.apply(this, arguments);
      this["import"](module);
      this.log("StormTracker constructor called " + global.config.datadir);
      this.certsdb = new CertificateRegistry("" + global.config.datadir + "/certs.db");
      this.agentsdb = new AgentsRegistry("" + global.config.datadir + "/agents.db");
      CertificateFactory = require("http/certs").CertificateFactory;
      this.CF = new CertificateFactory(this.certsdb);
      this.CF.init();
      this.AM = new AgentsManager(this.agentsdb, this.CF.CM);
    }

    StormTracker.prototype.run = function(config) {
      StormTracker.__super__.run.call(this, config);
      return console.log("Inside run.....");
    };

    return StormTracker;

  })(StormAgent);

  module.exports = StormTracker;

}).call(this);
